version: '3.9'
services:
  lr6_web_net:
    container_name: 'lr6_backend'
    restart: always
    ports:
      - '5000:5000'
    networks: 
      - lr6_net
    image: lr6_web_net
    build:
      context: .
    depends_on: 
      db:
        condition: service_healthy
  db:
    container_name: 'db'
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'CS_LR_MV22110702'
      MYSQL_ROOT_PASSWORD: '1111'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - lr6_net
networks:
    lr6_net:
        attachable: true
        driver: bridge
volumes:
    my-db: